name: build

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'
        required: true
        type: string

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [dev, prod]
        include:
          - env: dev
            branch: main
            commitChange: true
            createPR: false
          
          - env: prod
            branch: release/${{inputs.tags}}
            commitChange: true
            createPR: true

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          repository: gabriel-brotas/backstage-charts
          token: ${{ secrets.ACCESS_TOKEN }} 

      - name: Update helm image version
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: '${{ matrix.env }}/manifest.yaml'
          propertyPath: 'myapp.image.tag'
          value: ${{inputs.tags}}
          repository: gabriel-brotas/backstage-charts
          branch: main
          targetBranch: main
          commitChange: ${{ matrix.commitChange }}
          createPR: ${{ matrix.createPR }}
          updateFile: true
          message: 'update imageVersion'
          token: ${{ secrets.ACCESS_TOKEN }}
