name: build

on: 
  workflow_call:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [dev, prod]
        include:
          - env: dev
            commitChange: true
            createPR: false
          
          - env: prod
            commitChange: false
            createPR: true

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          repository: wexinc/global-backstage-helmcharts
          token: ${{ secrets.ACCESS_TOKEN }} 

      - name: Update helm image version
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: '${{ matrix.env }}/manifest.yaml'
          propertyPath: 'myapp.image.tag'
          value: '2.0.3'
          repository: gabriel-brotas/backstage-charts
          branch: main
          targetBranch: main
          commitChange: ${{ matrix.commitChange }}
          createPR: ${{ matrix.createPR }}
          updateFile: true
          message: 'update imageVersion'
          token: ${{ secrets.ACCESS_TOKEN }}
